// @generated by protoc-gen-connect-web v0.8.6 with parameter "target=ts"
// @generated from file chat.proto (package myapp, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ChatMessage, Empty, JoinResponse, User, UserList } from "./chat_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service myapp.ChatService
 */
export const ChatService = {
  typeName: "myapp.ChatService",
  methods: {
    /**
     * @generated from rpc myapp.ChatService.join
     */
    join: {
      name: "join",
      I: User,
      O: JoinResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc myapp.ChatService.sendMsg
     */
    sendMsg: {
      name: "sendMsg",
      I: ChatMessage,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc myapp.ChatService.receiveMsg
     */
    receiveMsg: {
      name: "receiveMsg",
      I: Empty,
      O: ChatMessage,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc myapp.ChatService.getAllUsers
     */
    getAllUsers: {
      name: "getAllUsers",
      I: Empty,
      O: UserList,
      kind: MethodKind.Unary,
    },
  }
} as const;

